Check that PETSc does not use 64bit indices.
IBAMR/IBAMR pull request #1311
Opened 2021-07-26 19:35 UTC by drwells

The usual checklist doesn't apply since this doesn't change the library.

2021-07-26 19:36 UTC, drwells commented
I tested this manually by putting the failing regex in `petscconf.h` myself.

2021-07-26 20:28 UTC, boyceg commented
It might not be that much work to make things work correctly with both 32- and 64-bit integers by compiling against a PETSc built with 64-bit integers and swapping `int`s for `PetscInt` as needed.

(Of course, we would need to have the CI test against both going forward to avoid regressions.)

2021-07-26 20:46 UTC, drwells commented
I don't think it's going to be that straightforward - even if we can compile and run programs there are probably limits in SAMRAI and IBAMR that we will run into only when we get into the billions of dofs range. This is a constant source of trouble in deal.II even though we have supported it for years.

2021-07-27 16:31 UTC, drwells commented
In fact, I don't think SAMRAI can handle this, since it doesn't support `long int` - we'd have to patch it if we want to use `PetscInt` for things like `constructPatchLevelDOFIndices`.

2021-07-31 19:33 UTC, boyceg requested changes
Can we also do this in the legacy autotools configure script?

2021-07-31 20:31 UTC, drwells commented
Sure

2021-08-02 20:45 UTC, drwells commented
Fixed!

2021-08-03 03:50 UTC, boyceg approved these changes

2021-08-03 13:33 UTC, merged