Phase change patch 2: variable coefficient and Marangoni surface tension
IBAMR/IBAMR pull request #1623
Opened 2023-07-04 05:13 UTC by amneetb

### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [ ] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [ ] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

2023-09-01 21:16 UTC, amneetb commented
@boyceg: Next stop patch 2. Should we rebase this branch against updated master or patch 1?

2023-09-05 03:34 UTC, boyceg commented
> @boyceg: Next stop patch 2. Should we rebase this branch against updated master or patch 1?

I think that either would work, but I think that I would recommend rebasing against master at this point since the P1 branch has been merged into master.

I also think that you might find that it works better to set these PRs to target the previous PR rather than master, so that it is easier to see the changes that are specific to each PR. I always get nervous about changing the target branch for PRs though...

2023-09-05 12:26 UTC, drwells commented
Lets just rebase against master at this point. That should be relatively straightforward - we just need to update the autotools files.

2023-09-06 18:28 UTC, Raamkrishnan commented
I rebased this branch against the updated master. This patch is ready for review. The previous surface tension implementation could only handle a constant surface tension coefficient. Now, we modified it in such a way that it could handle both variable and constant surface tension coefficients. The variable surface tension coefficient is computed through a callback function. We have also added a new class ```MarangoniSurfaceTensionForceFunction``` derived from ```SurfaceTensionForceFunction``` class to compute the Marangoni forcing due to the surface tension gradients. Please take a look.

2023-09-08 16:46 UTC, drwells requested changes
I have a few minor comments. There's a test that uses the new class in #1628 so lets fix these small things and then merge.

2023-09-08 16:46 UTC, drwells commented on include/ibamr/SurfaceTensionForceFunction.h
> +    double d_sigma = std::numeric_limits<double>::signaling_NaN(), d_num_interface_cells;
```suggestion
    double d_sigma = std::numeric_limits<double>::signaling_NaN(), d_num_interface_cells = std::numeric_limits<double>::signaling_NaN();
```

2023-09-08 16:46 UTC, drwells commented on include/ibamr/SurfaceTensionForceFunction.h
> +    int d_C_idx, d_phi_idx;
```suggestion
    int d_C_idx = IBTK::invalid_index, d_phi_idx = IBTK::invalid_index;
```

2023-09-08 16:46 UTC, drwells commented on src/navier_stokes/fortran/navier_stokes_surface_tension_forcing2d.f.m4
> +c     sigma will be multiplied later with F as F = sigma*F.
```suggestion
c     It is the caller's responsibility to multiply F by the (possibly
c     spatially-dependent) sigma coefficient
```

2023-09-08 16:46 UTC, drwells commented on src/navier_stokes/fortran/navier_stokes_surface_tension_forcing2d.f.m4
> +c     F = marangoni_coef * F.
```suggestion
c     It is the caller's responsibility to multiply F by the (possibly
c     spatially-dependent) Marangoni coefficient.
```

2023-09-09 13:11 UTC, drwells approved these changes

2023-09-09 13:11 UTC, merged