Phase change patch 4
IBAMR/IBAMR pull request #1625
Opened 2023-07-05 21:20 UTC by amneetb

Adding cell centered mass integrator using RK1/2 schemes to find the convective flux related to a transport quantity.

### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [ ] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [ ] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

2023-09-14 21:04 UTC, Raamkrishnan commented
Rebased this with the master and made the necessary changes in the ```AdvDiffConservativeMassScalarTransportRKIntegrator``` class. Please take a look.

2023-09-20 16:24 UTC, drwells requested changes
It looks like there aren't any tests for this class (though it is used indirectly in the tests in #1628). Could you add one which just integrates some quantity and then prints it out on a coarse grid?

2023-09-20 16:24 UTC, drwells commented on include/ibamr/AdvDiffConservativeMassScalarTransportRKIntegrator.h
> +#include "ibamr/STSMassFluxIntegrator.h"
```suggestion
#include <ibamr/config.h>

#include "ibamr/STSMassFluxIntegrator.h"
```
I need to finish the CI check to verify that the config header is always present - we always need it.

2023-09-20 16:24 UTC, drwells commented on include/ibamr/AdvDiffConservativeMassScalarTransportRKIntegrator.h
> + * Class AdvDiffConservativeMassScalarTransportRKIntegrator computes the convective
```suggestion
 * This class computes the convective
```

2023-09-20 16:24 UTC, drwells commented on include/ibamr/AdvDiffConservativeMassScalarTransportRKIntegrator.h
> +    std::vector<IBTK::HierarchyGhostCellInterpolation::InterpolationTransactionComponent> d_Q_transaction_comps,
```suggestion
    std::string d_transport_quantity_bdry_extrap_type = "CONSTANT", d_material_property_bdry_extrap_type = "CONSTANT";

    // Cached communications operators.
    std::vector<IBTK::HierarchyGhostCellInterpolation::InterpolationTransactionComponent> d_Q_transaction_comps,
```

2023-09-21 23:48 UTC, Raamkrishnan commented
> It looks like there aren't any tests for this class (though it is used indirectly in the tests in #1628). Could you add one which just integrates some quantity and then prints it out on a coarse grid?

This class is not a standalone integrator. It is tightly coupled to ```PhaseChangeHierarchyIntegrator``` class. I think the existing interface needs to be changed to add a test just for this class. As you noted, we have already added a test that uses both ```PhaseChangeHierarchyIntegrator``` and ```AdvDiffConservativeMassScalarTransportRKIntegrator.h``` in #1628.

2023-10-02 05:38 UTC, Raamkrishnan commented
@drwells Ping

2023-10-03 22:48 UTC, amneetb commented
@drwells : if all looks good can we merge this and move to the next patch?

2023-10-04 15:53 UTC, drwells commented
I have some ideas for how to test this - I'll open an issue for that and lets keep going.

2023-10-04 15:53 UTC, drwells approved these changes

2023-10-04 15:53 UTC, merged