fix examples/IB/explicit/ex6
IBAMR/IBAMR pull request #1632
Opened 2023-08-08 03:54 UTC by boyceg

Fixes `examples/IB/explicit/ex6`.

(I think that the usual checklist does not apply.)

2023-08-16 19:00 UTC, drwells approved these changes
Yup - the base class is responsible for allocating and deallocating those values.

2023-08-16 19:45 UTC, drwells requested changes
Actually, on further investigation - while these changes make sense the resulting visualization field has zero velocity and zero structure movement - that can't be right.

2023-08-16 19:45 UTC, drwells commented on examples/IB/explicit/ex6/IBSimpleHierarchyIntegrator.cpp
>          current_time, new_time, skip_synchronize_new_state_data, num_cycles);
This is in the wrong place - this class should postprocess its own data before calling the base class function. It's the opposite order as preprocessing (i.e., inner-outer-outer-inner).

2025-09-18 04:13 UTC, boyceg commented
@drwells, I think that this is fixed.

2025-09-18 14:59 UTC, drwells commented
I think you need to rebase - there's an extra commit in here.

2025-09-18 16:34 UTC, boyceg commented
Fixed.

2025-09-18 20:41 UTC, drwells commented
Could you post a screenshot of the velocity field you get here? I get all zeros for both velocity and pressure when I run this example.

2025-09-18 20:59 UTC, boyceg commented
That is what this one does — forces are zero and so nothing happens:
```
    // For simplicity, set the Lagrangian force density to equal zero.
    ierr = VecZeroEntries(d_F_data->getVec());
    IBTK_CHKERRQ(ierr);
```
I added this example many years ago for someone who wanted a simple IB time stepping algorithm implementation that students could use as a template for experimenting with alternative IB time stepping schemes.

2025-09-18 21:07 UTC, drwells commented
Ah - well, if its supposed to do that then let's merge!

2025-09-18 21:08 UTC, drwells approved these changes

2025-09-18 21:08 UTC, merged