Michaelli/ibfe/check mesh dim for IBFEMethod and IBSurfaceMethod
IBAMR/IBAMR pull request #1772
Opened 2024-11-18 19:07 UTC by Lianxiali

**Issue:** If a surface mesh is provided (a body mesh is needed) `IBFEMethod `can run but will fail with the error `"Assertion `length != static_cast<Real>(0.)' failed."`  This is coming from trying to make a vector of zero length a unit vector.

**Fix 1:** Check the mesh dimension in the constructors of `IBFEMethod `to make sure the mesh dimension is the same as the physical dimension.

**Fix 2:** Check the mesh dimension in the constructors of `IBFESurfaceMesh` to make sure the mesh dimension is 1 less than the physical dimension.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format (i.e., `make indent`) run? For more information see
      `scripts/formatting/README.md`.
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test or tests should be added. New tests should run quickly (less than a minute in release mode). If possible, an older test should gain a new option so that we do not need to compile more test executables.
- [ ] Did you (if your account has permission to do so) set relevant labels on GitHub for the pull request?

2024-11-20 21:07 UTC, drwells requested changes
Thanks for the fix. I have some minor suggestions.

2024-11-20 21:07 UTC, drwells commented on src/IB/IBFEMethod.cpp
> +    }
```suggestion
    // Check if the mesh dimension is compatible with the IBStrategy
    TBOX_ASSERT(mesh->mesh_dimension() == mesh->spatial_dimension());
```
This is the correct fix but we can cut out several intermediate steps.

2024-11-20 21:07 UTC, drwells commented on src/IB/IBFEMethod.cpp
> +    }
Same here and below.

2024-12-23 18:38 UTC, drwells commented
@Lianxiali want to take a look? If not I'll wrap this up.

2024-12-23 19:43 UTC, Lianxiali commented
Thank you for the suggestions. I just made the update. Please take a look at the commits again.

Do I need to request a merge? I don't know how to do that on my end.

2024-12-23 20:29 UTC, drwells requested changes
You don't need to request anything - everything will (or should) automatically re-run if you push changes to the branch.

2024-12-23 20:29 UTC, drwells commented on src/IB/IBFESurfaceMethod.cpp
> +    TBOX_ASSERT(mesh->mesh_dimension() == mesh->spatial_dimension() - 1);
We still need the loop here.

2024-12-23 20:29 UTC, drwells commented on src/IB/IBFEMethod.cpp
> +    TBOX_ASSERT(mesh->mesh_dimension() == mesh->spatial_dimension());
same thing.

2024-12-27 16:54 UTC, drwells approved these changes

2024-12-27 16:54 UTC, merged